### ISSUE TITLE
[BUG] Characters not printing

### ISSUE THREAD

**Issue by oraqlle** [Champii/Rock#88]
Rock currently has an issue printing literal characters of any kind. It currently throws an invalid syntax error for this input:

Input:

```zsh
main =
    print 'c'
```

Output:

```zsh
$ rock run
[Error] SyntaxError: Syntax error:
 -> ./src/main.rk(10:0)
     |
  10 | main =
     | ^~~~~~~~~~~~~~~~~~~~~
[Error] Compilation stopped with 1 errors and 0 warnings
```

It also has an issue print escape characters: Issue (#89)

**Comment by Champii** [comment]
Indeed, single char literals are not implemented yet.

The current workaround is to use string literals instead
```haskell
main = print "c"
```

This might be a good first feature for you if you want to get your hands dirty :)

**Comment by Champii** [comment]
Characters have been implemented.
However there is still a bug using the `print` method on chars, that is linked to a bug in the string index assignation (#115)
Closing in favor of this one
