### ISSUE TITLE
[BUG] Escape characters in strings not parsing correctly

### ISSUE THREAD

**Issue by oraqlle** [Champii/Rock#89]
When printing a string containing an ASCII escape sequence like `\n` or `\t`, it prints the literal characters of the sequence and doesn't result in the expected output. 

## Example

Input:

```zsh
main =
    print "Hello\nWorld"
```

Output:

```zsh
$ rock run
Hello\nWorld
```

## Note

Print an escape character in single quotes as if a single character throws an error. Related to issue (#88)

**Comment by Champii** [comment]
This is also expected as I didn't implement escaped strings yet.
I believe there is a builtin feature in [nom](https://github.com/Geal/nom), the parser Rock uses that can be of great help for that.
